Added arguments usage example
lubien/elixir-telegram-bot-boilerplate pull request #16
Opened 2019-03-21 17:47 UTC by v0idpwn

You could find something similar on the code but it was not clear. I had to use this and maybe it could help someone.

2019-03-21 18:39 UTC, lubien requested changes

2019-03-21 18:39 UTC, lubien commented on lib/app/commands.ex
> +  # You can emulate arguments acess through nadia's update.message
Typo "acess".

2019-03-21 18:39 UTC, lubien commented on lib/app/commands.ex
> +     [_command | args] = String.split(update.message.text, " ")
Wrong indent

2019-03-21 18:40 UTC, lubien commented
Hi there. It's something really useful for sure. Just need some fixes before merging.

2019-03-21 20:07 UTC, v0idpwn commented
fix'd. 

create more issues, i'm willing to help :)

2019-05-07 12:40 UTC, lubien approved these changes

2019-05-07 12:40 UTC, merged

2019-05-07 12:40 UTC, lubien commented
Lovely. Thank you.

Also sorry for the delay